### PR TITLE
MLEM - DVC interaction update

### PR DESCRIPTION
**Pull request by igordertigor**
This is referring to #205.

### CODE REVIEW

**Comment by aguschin** [comment]
Thanks! Looks good. I'm going to fix listing + reformat the page a bit.

**Review by aguschin — APPROVED** [review]

**Comment by aguschin** [comment]
@rogermparent @julieg18
I wonder why this was not deployed? It's because the PR is from external repo? Can we maybe trigger these manually in that case?

**Comment by rogermparent** [comment]
Yeah, both Heroku and GH Actions don't like to operate on forks. This has been brought up recently so we can consider this another request on the pile. Using `pull_request_target` to run our prettier/eslint CI is achievable, but getting the Heroku deploy to run is another question entirely.

**Comment by aguschin** [comment]
Thanks @rogermparent. Do we have an issue somewhere to link this one to it?

**Comment by rogermparent** [comment]
Not currently, I’m not sure which repo we'd put it on considering it affects every site. I'll figure that out and spin one up!

**Comment by yathomasi** [comment]
We do have an issue on dvc.org:  https://github.com/iterative/dvc.org/issues/3970

**Pull request merged**
